### ISSUE TITLE
chore

### ISSUE THREAD

**Issue by bjarneo** [eggheadio/egghead-redux-transcripts#1]
Chore? Store?

https://github.com/eggheadio/egghead-redux-transcripts/blob/master/javascript-redux-passing-the-store-down-implicitly-via-context.md

**Comment by gaearon** [comment]
The sole reason this repo was put out is so you can submit pull requests fixing mistakes. :wink:

**Comment by bjarneo** [comment]
Sure I can fix it. Just had to confirm :)
